---
- name: install/uninstall s/w app
  hosts: all
  become: yes
  vars:
    - a: git
    - b: present
    - c: yes  
  tasks: 
    - name: install/uninstall
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...          
