---
- name: Implementing loops
  hosts: all
  tasks:
    - name: Install,uninstall software applications
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: git,b: present,c: no}
        - {a: tree,b: absent,c: no} 
        - {a: maven,b: latest,c: yes}
... 
    
