---
- name: install/uninstall softwares applications
  hosts: all
  tasks:
    - name: install/uninstall
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...          
